using Content.Client.Administration.Managers;
using Content.Client.Audio;
using Content.Shared._White.Bark;
using Content.Shared._White.Bark.Systems;
using Content.Shared._White.CCVar;
using Content.Shared.CCVar;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Range = Robust.Client.UserInterface.Controls.Range;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AudioTab : Control
{
    [Dependency] private readonly IAudioManager _audio = default!;
    [Dependency] private readonly IClientAdminManager _admin = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public AudioTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CharVoiceType.AddItem(Loc.GetString("char-voice-none"), (int) CharacterVoiceType.None);
        CharVoiceType.AddItem(Loc.GetString("char-voice-bark"), (int) CharacterVoiceType.Bark);
        // CharVoiceType.AddItem(Loc.GetString("char-voice-tts"), (int) CharacterVoiceType.TTS);

        CharVoiceType.OnItemSelected += args =>
        {
            CharVoiceType.SelectId(args.Id);
            _cfg.SetCVar(WhiteCVars.CharVoiceType, (CharacterVoiceType) args.Id);
            _cfg.SaveSerializer();
        };
        CharVoiceType.SelectId((int) _cfg.GetCVar(WhiteCVars.CharVoiceType));

        // TtsVolumeSlider.OnValueChanged += _ => UpdateWork();
        BarkVolumeSlider.OnValueChanged += _ => UpdateWork();
        BarkLimitSlider.OnValueChanged += _ => UpdateWork();

        // TtsVolumeSlider.Value = _cfg.GetCVar(WhiteCVars.TTSVolume) * 100f;
        BarkVolumeSlider.Value = _cfg.GetCVar(WhiteCVars.BarkVolume) * 100f;
        BarkLimitSlider.Value = _cfg.GetCVar(WhiteCVars.BarkLimit);

        var masterVolume = Control.AddOptionPercentSlider(
            CVars.AudioMasterVolume,
            SliderVolumeMaster,
            scale: ContentAudioSystem.MasterVolumeMultiplier);
        masterVolume.ImmediateValueChanged += OnMasterVolumeSliderChanged;

        Control.AddOptionPercentSlider(
            CVars.MidiVolume,
            SliderVolumeMidi,
            scale: ContentAudioSystem.MidiVolumeMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbientMusicVolume,
            SliderVolumeAmbientMusic,
            scale: ContentAudioSystem.AmbientMusicMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbienceVolume,
            SliderVolumeAmbience,
            scale: ContentAudioSystem.AmbienceMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.LobbyMusicVolume,
            SliderVolumeLobby,
            scale: ContentAudioSystem.LobbyMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.InterfaceVolume,
            SliderVolumeInterface,
            scale: ContentAudioSystem.InterfaceMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AnnouncerVolume,
            SliderVolumeAnnouncer,
            scale: ContentAudioSystem.AnnouncerMultiplier);

        Control.AddOptionSlider(
            CCVars.MaxAmbientSources,
            SliderMaxAmbienceSounds,
            _cfg.GetCVar(CCVars.MinMaxAmbientSourcesConfigured),
            _cfg.GetCVar(CCVars.MaxMaxAmbientSourcesConfigured));


        Control.AddOptionCheckBox(CCVars.LobbyMusicEnabled, LobbyMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.RestartSoundsEnabled, RestartSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.EventMusicEnabled, EventMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.AnnouncerDisableMultipleEnabled, AnnouncerDisableMultipleSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.AdminSoundsEnabled, AdminSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.BwoinkSoundEnabled, BwoinkSoundCheckBox);

        Control.Initialize();
        UpdateWork();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _admin.AdminStatusUpdated += UpdateAdminButtonsVisibility;
        UpdateAdminButtonsVisibility();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _admin.AdminStatusUpdated -= UpdateAdminButtonsVisibility;
    }

    private void UpdateWork()
    {
        // _cfg.SetCVar(WhiteCVars.TTSVolume, TtsVolumeSlider.Value / 100f);
        _cfg.SetCVar(WhiteCVars.BarkVolume, BarkVolumeSlider.Value / 100f);
        _cfg.SetCVar(WhiteCVars.BarkLimit, (int) BarkLimitSlider.Value);
        _cfg.SaveSerializer();

        // TtsVolumeSlider.Text = Loc.GetString("ui-options-volume-percent", ("volume", (int)TtsVolumeSlider.Value));
        BarkVolumeSlider.Text = Loc.GetString("ui-options-volume-percent", ("volume", (int)BarkVolumeSlider.Value));
        BarkLimitSlider.Text = ((int) BarkLimitSlider.Value).ToString();
    }

    private void UpdateAdminButtonsVisibility()
    {
        BwoinkSoundCheckBox.Visible = _admin.IsActive();
        AdminSoundsCheckBox.Visible = _admin.IsActive();
    }

    private void OnMasterVolumeSliderChanged(Range range)
    {
        // TODO: I was thinking of giving OptionsTabControlRow a flag to "set CVar immediately", but I'm deferring that
        // until there's a proper system for enforcing people don't close the window with pending changes.
        // _audio.SetMasterGain(value);
        _audio.MainVolume = range.Value / 100f * ContentAudioSystem.MasterVolumeMultiplier;
    }
}
