":crayon: Спрайты :crayon:":
- changed-files:
  - any-glob-to-any-file: '**/*.rsi/*.png'

":world_map: Карты/Гриды :world_map:":
- changed-files:
  - any-glob-to-any-file:
    - 'Resources/Maps/**/*.yml'
    - 'Resources/Prototypes/Maps/**/*.yml'

":window: UI :window:":
- changed-files:
  - any-glob-to-any-file: '**/*.xaml*'

":desert_island: Шейдеры :desert_island:":
- changed-files:
  - any-glob-to-any-file: '**/*.swsl'

":sound: Звук :sound:":
- changed-files:
  - any-glob-to-any-file: '**/*.ogg'

":x: Нет C# :x:":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files: "!**/*.cs"

":shark: C# :shark:":
- changed-files:
  # Equiv to any-glob-to-all as long as this has one matcher. If ALL changed files are not C# files, then apply label.
  - all-globs-to-all-files: "**/*.cs"

":floppy_disk: Прототипы YAML :floppy_disk:":
- changed-files:
  - any-glob-to-any-file: "**/*.yml"
  - any-glob-to-any-file:
    - '!Resources/Maps/**/*.yml'
    - '!Resources/Prototypes/Maps/**/*.yml'

":bookmark_tabs: Локализация :bookmark_tabs:":
- changed-files:
  - any-glob-to-any-file: "**/*.ftl"

