// SPDX-FileCopyrightText: 2024 BombasterDS <115770678+BombasterDS@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Misandry <mary@thughunt.ing>
// SPDX-FileCopyrightText: 2025 gus <august.eymann@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Client.Administration.TimeTransferPanel;

[GenerateTypedNameReferences]
public sealed partial class TimeTransferEntry : BoxContainer
{
    public string JobName;
    public string PlaytimeTracker;

    public TimeTransferEntry(JobPrototype jobProto, SpriteSystem spriteSystem, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PlaytimeTracker = jobProto.PlayTimeTracker;
        JobLabel.Text = jobProto.LocalizedName;
        JobName = jobProto.LocalizedName;

        if (prototypeManager.TryIndex(jobProto.Icon, out var jobIcon))
            JobIcon.Texture = spriteSystem.Frame0(jobIcon.Icon);
    }

    public void UpdateGroupVisibility(bool inGrouped)
    {
        TimeLabel.Visible = !inGrouped;
        TimeEdit.Visible = !inGrouped;
        GroupCheckbox.Visible = inGrouped;
    }

    public string GetJobTimeString() => TimeEdit.Text != null ? TimeEdit.Text : "";

    public bool InGroup() => GroupCheckbox.Pressed;
}
