using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Guidebook;
using Content.Client.Lobby;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client._Orehum.Lobby.UI;

//
// License-Identifier: AGPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    public event Action<ProtoId<SpeciesPrototype>>? ChooseAction;
    public ProtoId<SpeciesPrototype> CurrentSpecies;

    public HumanoidCharacterProfile Profile;
    private readonly IEntityManager _entity;
    private readonly IPrototypeManager _proto;
    private readonly LobbyUIController _uIController;
    private readonly IResourceManager _resMan;
    [Dependency] private readonly DocumentParsingManager _parsingMan = default!;
    [Dependency] private readonly IRobustRandom _random = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public SpeciesWindow(HumanoidCharacterProfile profile,
                        IPrototypeManager proto,
                        IEntityManager ent,
                        LobbyUIController uIController,
                        IResourceManager resManager,
                        DocumentParsingManager parsing)
    {
        RobustXamlLoader.Load(this);
        _parsingMan = parsing;

        Select.OnPressed += _ => ChooseAction?.Invoke(CurrentSpecies);

        Title = Loc.GetString("species-window-title");

        Profile = profile;
        _entity = ent;
        _proto = proto;
        _uIController = uIController;
        _resMan = resManager;

        var protoList = _proto.EnumeratePrototypes<SpeciesPrototype>().Where(x => x.RoundStart).ToList();
        protoList.Sort((x, y) => string.Compare(Loc.GetString(x.Name), Loc.GetString(y.Name), StringComparison.CurrentCulture));

        AddLabel(Loc.GetString("species-category-label-classic"));
        foreach (var item in protoList.Where(x => x.Category == SpeciesCategory.Classic))
        {
            var button = new SpeciesButton(item)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = Profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += args => SelectSpecies(item.ID);
            SpeciesContainer.AddChild(button);
        }

        AddLabel(Loc.GetString("species-category-label-unusual"));
        foreach (var item in protoList.Where(x => x.Category == SpeciesCategory.Unusual))
        {
            var button = new SpeciesButton(item)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = Profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += args => SelectSpecies(item.ID);
            SpeciesContainer.AddChild(button);
        }

        AddLabel(Loc.GetString("species-category-label-special"));
        foreach (var item in protoList.Where(x => x.Category == SpeciesCategory.Special))
        {
            var button = new SpeciesButton(item)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = Profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += args => SelectSpecies(item.ID);
            SpeciesContainer.AddChild(button);
        }

        CurrentSpecies = Profile.Species;
        SelectSpecies(Profile.Species);
    }

    private string LocOrLiteral(string id)
        => _loc.TryGetString(id, out var value) ? value : id;

    private void AddLabel(string text)
    {
        var container = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
        };
        var label = new Label()
        {
            Text = text,
            StyleClasses = { "LowDivider" },
            Margin = new(2f, 2f),
            HorizontalAlignment = HAlignment.Center,
        };
        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };
        container.AddChild(label);
        container.AddChild(separator);

        SpeciesContainer.AddChild(container);
    }

    public void SelectSpecies(ProtoId<SpeciesPrototype> protoId)
    {
        DetailInfoContainer.DisposeAllChildren();

        foreach (var item in SpeciesContainer.Children)
        {
            if (item is not SpeciesButton button)
                continue;
            button.Pressed = protoId == button.Proto;
        }

        var proto = _proto.Index(protoId);
        var job = Profile.JobPriorities.Where(x => x.Value == JobPriority.High).First().Key;
        CurrentSpecies = protoId;

        var previewProfile = Profile;
        previewProfile = previewProfile.WithSpecies(protoId);

        previewProfile = previewProfile.WithCharacterAppearance(
            HumanoidCharacterAppearance.EnsureValid(previewProfile.Appearance, protoId, previewProfile.Sex, []));

        var skin = proto.SkinColoration;
        var skinType = _proto.Index(protoId).SkinColoration;
        var strategy = _proto.Index(skinType).Strategy;

        var newSkinColor = strategy.InputType switch
        {
            SkinColorationStrategyInput.Unary => strategy.FromUnary(_random.NextFloat(0f, 100f)),
            SkinColorationStrategyInput.Color => strategy.ClosestSkinColor(new Color(_random.NextFloat(1), _random.NextFloat(1), _random.NextFloat(1), 1)),
            _ => strategy.ClosestSkinColor(new Color(_random.NextFloat(1), _random.NextFloat(1), _random.NextFloat(1), 1)),
        };

        var mob = _uIController.LoadProfileEntity(previewProfile, _proto.Index(job), false);  // Раздетый моб
        Mob.SetEntity(mob);

        var loadoutMob = _uIController.LoadProfileEntity(previewProfile, _proto.Index(job), true);    // Моб в одежде должности
        JobLoadout.SetEntity(loadoutMob);

        Select.Disabled = Profile.Species == protoId;
        Select.OnPressed += args => ChooseAction?.Invoke(protoId);

        var prosConsContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
            MaxWidth = 380f,
        };
        var prosConsLabel = new RichTextLabel()
        {
            Text = Loc.GetString("ui-species-pros-cons"),
            StyleClasses = { "LowDivider" },
            Margin = new(2f, 2f),
        };
        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };
        prosConsContainer.AddChild(prosConsLabel);
        prosConsContainer.AddChild(separator);
        DetailInfoContainer.AddChild(prosConsContainer);

        if (proto.Pros.Count <= 0 && proto.Special.Count <= 0 && proto.Cons.Count <= 0)
        {
            var noProsConsLabel = new RichTextLabel()
            {
                Text = Loc.GetString("ui-species-no-pros-cons"),
                Margin = new(4f),
            };
            DetailInfoContainer.AddChild(noProsConsLabel);
        }
        else
        {
            if (proto.Pros.Count > 0)
            {
                foreach (var item in proto.Pros)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#13f244]- " + LocOrLiteral(item) + "[/color]",
                        StyleClasses = { "LowDivider" },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Special.Count > 0)
            {
                foreach (var item in proto.Special)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "- " + LocOrLiteral(item),
                        StyleClasses = { "LowDivider" },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }

            if (proto.Cons.Count > 0)
            {
                foreach (var item in proto.Cons)
                {
                    var label = new RichTextLabel()
                    {
                        Text = "[color=#d63636]- " + LocOrLiteral(item) + "[/color]",
                        StyleClasses = { "LowDivider" },
                        Margin = new(4f, 2f),
                    };
                    prosConsContainer.AddChild(label);
                }
                prosConsContainer.AddChild(new Control() { MinHeight = 8f });
            }
        }

        if (!proto.Description.HasValue)
            return;

        using var file = _resMan.ContentFileReadText(proto.Description.Value);
        _parsingMan.TryAddMarkup(DetailInfoContainer, file.ReadToEnd());
    }

    private sealed partial class SpeciesButton(ProtoId<SpeciesPrototype> proto) : Button
    {
        public ProtoId<SpeciesPrototype> Proto = proto;
    }
}
