// SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Tayrtahn <tayrtahn@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Shared.Prototypes;

namespace Content.Shared.Procedural;

[Virtual] [DataDefinition]
public partial class DungeonConfig
{
    /// <summary>
    /// The secret sauce, procedural generation layers that get run.
    /// </summary>
    [DataField]
    public List<IDunGenLayer> Layers = new();

    /// <summary>
    /// Maximum times to run the config.
    /// </summary>
    [DataField]
    public int MaxCount = 1;

    /// <summary>
    /// Maximum amount we can offset the dungeon by.
    /// </summary>
    [DataField]
    public int MaxOffset;

    /// <summary>
    /// Minimum times to run the config.
    /// </summary>
    [DataField]
    public int MinCount = 1;

    /// <summary>
    /// Minimum amount we can offset the dungeon by.
    /// </summary>
    [DataField]
    public int MinOffset;

    /// <summary>
    /// Should we reserve the tiles generated by this config so no other dungeons can spawn on it within the same job?
    /// </summary>
    [DataField]
    public bool ReserveTiles;
}

[Prototype]
public sealed class DungeonConfigPrototype : DungeonConfig, IPrototype
{
    [IdDataField]
    public string ID { get; } = default!;
}
