using Content.Shared._White.SpeciesDictionary;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._White.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class SpeciesGroupContainer : Control
{
    private readonly List<(Button, Action<BaseButton.ButtonEventArgs>)> _buttonsEvents = new();
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public SpeciesGroupContainer()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public Action<ProtoId<SpeciesPrototype>>? OnSpeciesSelected { get; set; }

    public void Initialize(SpeciesDictionaryGroupPrototype group)
    {
        Clear();

        GroupLabel.Text = Loc.GetString($"species-window-group-{group.ID.ToLower()}");
        foreach (var species in _prototypeManager.EnumeratePrototypes<SpeciesDictionaryPrototype>())
        {
            if (species.GroupPrototype != group.ID)
                continue;

            if (!_prototypeManager.TryIndex<SpeciesPrototype>(species.ID, out var speciesPrototype) ||
                !speciesPrototype.RoundStart)
                continue;

            var button = new Button
            {
                Text = Loc.GetString($"species-name-{species.ID.ToLower()}"),
                HorizontalAlignment = HAlignment.Stretch,
            };

            if (group.Color.HasValue)
                button.Modulate = group.Color.Value;

            Action<BaseButton.ButtonEventArgs> onSelected = _ =>
                OnSpeciesSelected?.Invoke(new ProtoId<SpeciesPrototype>(species.ID));
            button.OnPressed += onSelected;
            _buttonsEvents.Add((button, onSelected));
            SpeciesButtonContainer.AddChild(button);
        }
    }

    public void Clear()
    {
        foreach (var (button, eventInternal) in _buttonsEvents)
        {
            button.OnPressed -= eventInternal;
        }

        _buttonsEvents.Clear();

        SpeciesButtonContainer.Children.Clear();
    }
}
