# Tabs

- type: quickPhrase
  id: BaseCommonPhrase
  tab: Стандартные фразы
  abstract: true

- type: quickPhrase
  id: BaseJobPhrase
  tab: Профессии
  abstract: true

- type: quickPhrase
  id: BaseLocationPhrase
  tab: Локации
  abstract: true

- type: quickPhrase
  id: BaseSubjectPhrase
  tab: Предметы
  abstract: true

- type: quickPhrase
  id: BaseThreatPhrase
  tab: Надеждность
  abstract: true

- type: quickPhrase
  id: BaseSpeciesPhrase
  tab: Разное
  abstract: true

# Departments

- type: quickPhrase
  id: BaseCivilianPhrase
  group: Гражданские
  abstract: true

- type: quickPhrase
  id: BaseCommandPhrase
  group: Коммандование
  styleClass: CommandButton
  abstract: true

- type: quickPhrase
  id: BaseEngineeringPhrase
  group: Инженерия
  styleClass: EngineeringButton
  abstract: true

- type: quickPhrase
  id: BaseEpistemicsPhrase
  group: Ученые
  styleClass: EpistemicsButton
  abstract: true

- type: quickPhrase
  id: BaseJusticePhrase
  group: Нотариус
  styleClass: JusticeButton
  abstract: true

- type: quickPhrase
  id: BaseLogisticsPhrase
  group: Карго
  styleClass: LogisticsButton
  abstract: true

- type: quickPhrase
  id: BaseMedicalPhrase
  group: Врачи
  styleClass: MedicalButton
  abstract: true

- type: quickPhrase
  id: BaseSecurityPhrase
  group: СБ
  styleClass: SecurityButton
  abstract: true

- type: quickPhrase
  id: BaseServicePhrase
  group: Сервис
  styleClass: ServiceButton
  abstract: true
