// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 SlamBamActionman <83650252+SlamBamActionman@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Implants.UI;

[GenerateTypedNameReferences]
public sealed partial class DeimplantChoiceWindow : FancyWindow
{
    private string? _chosenImplant;

    private Dictionary<string, string> _implants = new();
    public Action<string?>? OnImplantChange;

    public DeimplantChoiceWindow()
    {
        RobustXamlLoader.Load(this);

        ImplantSelector.OnItemSelected += args =>
        {
            OnImplantChange?.Invoke(_implants.ElementAt(args.Id).Key);
            ImplantSelector.SelectId(args.Id);
        };
    }

    public void UpdateImplantList(Dictionary<string, string> implants)
    {
        _implants = implants;
        var i = 0;
        ImplantSelector.Clear();
        foreach (var implantDict in _implants)
        {
            ImplantSelector.AddItem(implantDict.Value, i);
            i++;
        }
    }

    public void UpdateState(string? implant)
    {
        _chosenImplant = implant;

        for (var id = 0; id < ImplantSelector.ItemCount; id++)
        {
            if (_implants.ElementAt(id).Key.Equals(_chosenImplant))
            {
                ImplantSelector.SelectId(id);
                break;
            }
        }
    }
}
