# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Blob
  name: roles-antag-blob-name
  antagonist: true
  setPreference: true
  objective: roles-antag-blob-objective
  guides: [ Blob ]
  requirements:
  - !type:OverallPlaytimeRequirement
<<<<<<< HEAD
    time: 5h
  creditImage: /Textures/_Trauma/EndCredits/Antags/blob.png
=======
    time: 5h # 5h # Goobstation-RoleTime
>>>>>>> 819ff6845d52b21ce5da31a61760b81c6d1aa75f
